# This field specifies the scheduler that will be started automatically when scx_loader starts (e.g., on boot).
#default_sched = "scx_flash"

# This field specifies the mode which will be used when scx_loader starts (e.g., on boot).
#default_mode = "Auto"

# This "structure" allows configuring flags for each scheduler mode of particular scx scheduler
#[scheds.'scheduler']
#auto_mode = []
#gaming_mode = []
#lowlatency_mode = []
#powersave_mode = []
#server_mode = []
