[package]
name = "scx_raw_pmu"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.65"
csv = "1.3.1"
include_dir = "0.7.4"
procfs = "0.15.1"
regex = "1.11.2"
scx_utils = { path = "../scx_utils", version = "1.0.19" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.19.1"

[build-dependencies]
scx_utils = { path = "../scx_utils", version = "1.0.19" }
